### ISSUE TITLE
service annotations

### ISSUE THREAD

**Issue by disser4** [wallarm/pgbouncer-chart#6]
``` annotations:
    {{- range $key, $value := .Values.service.annotations }}
      {{ $key }}: {{ $value | quote }}
    {{- end }}
   ``` 
    Can you guys add this to templates/service.yaml
    
    Thanks

**Comment by apollotonkosmo** [comment]
https://github.com/wallarm/pgbouncer-chart/pull/8 @disser4  I have created this PR in regards to this is issue.
